# Generated by Django 5.2.6 on 2025-09-20 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('brandCertLink', models.URLField(blank=True, null=True)),
                ('brandLicenceLink', models.URLField(blank=True, null=True)),
                ('dosageForm', models.CharField(blank=True, max_length=100, null=True)),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('activeingredients', models.JSONField(blank=True, help_text='List of active ingredients as JSON list', null=True)),
                ('gtin', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('batch', models.CharField(blank=True, max_length=100, null=True)),
                ('manufactureDate', models.DateField(blank=True, null=True)),
                ('expiryDate', models.DateField(blank=True, null=True)),
                ('StorageConditions', models.TextField(blank=True, null=True)),
                ('regulatoryInfo', models.TextField(blank=True, null=True)),
                ('imageExample', models.ImageField(blank=True, null=True, upload_to='pharmacy_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
