# Generated by Django 5.2.6 on 2025-09-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
