# Generated by Django 5.2.6 on 2025-09-21 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_group_pharmacy_price_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.group'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='price_group',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
