# Generated by Django 5.2.6 on 2025-09-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_pharmacy_group_alter_pharmacy_price_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='price_group',
            new_name='cost_status',
        ),
    ]
